library(readr)
library(tidyverse)
caminho_pasta <- "Data-Raw/Pagamento Mensal"
arquivos_csv <- list.files(caminho_pasta, pattern = ".CSV", full.names = TRUE)
pagamentos <- data.frame()
for (arquivo in arquivos_csv) {
  dados <- read_delim(arquivo, 
                      delim = ";", escape_double = FALSE, locale = locale(decimal_mark = ",", 
                                                                          grouping_mark = ".", encoding = "ISO-8859-2"), 
                      na = "NA", trim_ws = TRUE)
  dados$nome_arquivo <- gsub(".CSV", "", basename(arquivo))
  dados$nome_arquivo <- gsub("DESPESA_PAGA_EM_", "", basename(dados$nome_arquivo))
  dados[9] <- NULL
  dados[8] <- NULL
  dados[2] <- NULL
  dados[1] <- NULL
  dados <- rename(dados, CPF_CNPJ = 'CPF/CNPJ Fornecedor')
  dados <- rename(dados, Valor_Pago = 'Valor Pago')
  dados <- rename(dados, Data = 'nome_arquivo')
  dados$Data <- gsub("0217", "2017", dados$Data)
  dados$Data <- paste0(substring(dados$Data, 1, 2), "/", substring(dados$Data, 3))
  pagamentos <- rbind(pagamentos, dados)
  pagamentos <- subset(pagamentos, Valor_Pago != 0.00)
  rm(arquivo)
  rm(arquivos_csv)
  rm(caminho_pasta)
  rm(dados)
}
pagamentos <- rename(pagamentos, Favorecido = Fornecedor)
pagamentos$Favorecido <- gsub("IZABELLI", "IZABELLE", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("ALEXKELLY PINHEIRO MOREIRA DE SOUZA", "ALEXKELLY PINHEIRO MOREIRA", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("ROSANGELA KALINA VELOSO DA SILVA", "ROSANGELA KALINA VELOSO DA SILVA CARVALHO DE LIMA", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("THEOFILLO MATEUS VARELA LIBERATO", "THEOFILLO MATHEUS VARELA LIBERATO", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("MARCOS EVANGELISTA ARAUJO", "MARCOS EVANGELISTA DE ARAUJO", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("LEANDRO LINCONL NEVES", "LEANDRO LINCOLN SANTOS NEVES", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("JOSUELBERTH CUNHA RODRIGUES MATOS", "JOSUELBERTH CUNHA RODRIGUES DE MATOS", pagamentos$Favorecido)
pagamentos$Favorecido <- gsub("KARLA SIMONE FELIPE DA PENHA", "KARLA SIMONE FELIPE DA PENHA MONTENEGRO", pagamentos$Favorecido)
pagamentos <- apply(pagamentos, 2, trimws)
pagamentos <- as.data.frame(pagamentos)
pagamentos$Data <- as.Date(paste("01", pagamentos$Data, sep = "/"), format = "%d/%m/%Y")
pagamentos <- pagamentos %>%
  mutate_all(toupper)
pagamentos <- data.frame(lapply(pagamentos, function(x) iconv(x, "UTF-8", "ASCII//TRANSLIT")))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("  ", " ", x)))
pagamentos$Valor_Pago <- as.numeric(pagamentos$Valor_Pago)
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("EIRELLI", "EIRELI", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDA-ME", "LTDA ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDA-EPP", "LTDA EPP", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("S/A", "SA", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("EIRELI-ME", "EIRELI ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDA.", "LTDA", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDAME", "LTDA ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("-ME", " ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("- ME", "ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDA-EPP", "LTDA EPP", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDAEPP", "LTDA EPP", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("LTDAME", "LTDA ME", x)))
pagamentos <- data.frame(lapply(pagamentos, function(x) gsub("DEPARTAMENTO ESTADUALE TRANSITOO RN -ETRAN", "DEPARTAMENTO ESTADUAL DE TRANSITO RN - DETRAN", x)))
pagamentos$Favorecido <- gsub("J. FRENANDES NETO LTDA", "J. FERNANDES NETO LTDA", pagamentos$Favorecido)
#
lista_geral <- readRDS("Data/lista_geral.rds")
pagamentos <- left_join(pagamentos, lista_geral, by = "Favorecido")
rm(lista_geral)
colnames(pagamentos)[which(names(pagamentos) == "id.y")] <- "id"
#
pagamentos <- pagamentos %>% group_by(id) %>% mutate(Primeiro_Pgto = min(as.Date(Data)))
pagamentos <- pagamentos %>% group_by(id) %>% mutate(Ultimo_Pgto = max(as.Date(Data)))
pagamentos$Meses <- round(as.numeric(difftime(as.Date(pagamentos$Ultimo_Pgto), as.Date(pagamentos$Primeiro_Pgto), units = "days")) / 30.44)
pagamentos$Meses <- pmax(pagamentos$Meses, 1)
pagamentos$Primeiro_Pgto <- as.Date(pagamentos$Primeiro_Pgto, "%Y")
pagamentos$Ultimo_Pgto <- as.Date(pagamentos$Ultimo_Pgto, "%Y")
pagamentos$Primeiro_Pgto <- format(pagamentos$Primeiro_Pgto, "%Y")
pagamentos$Ultimo_Pgto <- format(pagamentos$Ultimo_Pgto, "%Y")
dadosv <- pagamentos
dadosv$Vinculo <- ifelse(dadosv$Natureza == 339093, "ELETIVO", 
  ifelse(dadosv$Natureza == 319011, "FOLHA DE PAGAMENTO", 
  ifelse(dadosv$Natureza == 339039 & nchar(dadosv$CPF_CNPJ) != 18, "PRESTADOR PF",
  ifelse(dadosv$Natureza == 339036 & nchar(dadosv$CPF_CNPJ) != 18, "PRESTADOR PF",
  ifelse(dadosv$Natureza == 339030 & nchar(dadosv$CPF_CNPJ) != 18, "PRESTADOR PF",
  ifelse(dadosv$Natureza == 449051 & nchar(dadosv$CPF_CNPJ) == 18, "PRESTADOR PJ",
  ifelse(dadosv$Natureza == 339039 & nchar(dadosv$CPF_CNPJ) == 18, "PRESTADOR PJ",
  ifelse(dadosv$Natureza == 449052 & nchar(dadosv$CPF_CNPJ) == 18, "PRESTADOR PJ",
  ifelse(dadosv$Natureza == 339034 & nchar(dadosv$CPF_CNPJ) == 18, "PRESTADOR PJ",
  ifelse(dadosv$Natureza == 339030 | dadosv$Natureza == 339032 | dadosv$Natureza == 339033 & nchar(dadosv$CPF_CNPJ) == 18, "PRESTADOR PJ", ""))))))))))
df_vereador <- subset(dadosv, grepl("ELETIVO", Vinculo))
dadosv$Vinculo <- ifelse(!is.na(match(dadosv$Favorecido, df_vereador$Favorecido)), "ELETIVO", dadosv$Vinculo)
dadosv$Vinculo <- ifelse(grepl("FOLHA", pagamentos$Favorecido), "FOLHA", dadosv$Vinculo)
dadosv$Vinculo <- ifelse(grepl("DIARIAS", pagamentos$Favorecido), "DIARIAS", dadosv$Vinculo)
folha <- readRDS("Data/folha.rds")
dadosv$Vinculo <- ifelse(grepl("/", dadosv$CPF_CNPJ), ifelse(grepl("", dadosv$Vinculo), "PRESTADOR PJ", dadosv$Vinculo), dadosv$Vinculo)
dadosv$Vinculo <- ifelse(grepl("INSS", dadosv$Favorecido), "PREVIDENCIA", dadosv$Vinculo)
dadosv$Vinculo <- ifelse(grepl("PREFEITURA MUNICIPAL DE PARNAMIRIM", dadosv$Favorecido), "PREVIDENCIA", dadosv$Vinculo)
dadosv$Vinculo <- ifelse(grepl("URSULA CRISTINA GADELHA AIRES DE MEDEIROS", dadosv$Favorecido), "PRESTADOR PF", dadosv$Vinculo)
dadosv$Vinculo[dadosv$Vinculo == ""] <- folha$Vinculo[match(dadosv$Favorecido[dadosv$Vinculo == ""], folha$Favorecido)]
dadosv$Vinculo <- ifelse(grepl("URSULA CRISTINA GADELHA AIRES DE MEDEIROS", dadosv$Favorecido), "PRESTADOR PF", dadosv$Vinculo)
dadosv_vazias <- subset(dadosv, is.na(Vinculo))
dadosv$Vinculo <- ifelse(grepl("PREF.MUN. DE PARNAMIRIM-ISS", dadosv$Favorecido), "IMPOSTOS", dadosv$Vinculo)
pagamentos <- dadosv
ajuste_vereador_comissionado <- pagamentos$Favorecido == "SHEILLA CRISTINA CUNHA DE ANDRADE" & pagamentos$Data >= as.Date("2017-05-01")
pagamentos$Vinculo[ajuste_vereador_comissionado] <- "COMISSIONADO"
#
folha_vinculo <- folha[, c("id", "Data", "Vinculo")]
pagamentos <- merge(pagamentos, folha_vinculo, by = c("id", "Data"), all.x = TRUE)
pagamentos$Vinculo <- ifelse(is.na(pagamentos$Vinculo.y), pagamentos$Vinculo.x, pagamentos$Vinculo.y)
pagamentos <- subset(pagamentos, select = -c(Vinculo.x, Vinculo.y))
rm(folha)
rm(ajuste_vereador_comissionado)
rm(df_vereador)
rm(folha_vinculo)
rm(dadosv)
rm(dadosv_vazias)
#
pagamentos$Objeto <- NA
pagamentos$Objeto <- ifelse(pagamentos$Natureza == 319011, "FOLHA DE PAGAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Natureza == 339034, "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Natureza == 319011, "FOLHA DE PAGAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Natureza == 319094, "FOLHA DE PAGAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Elemento == "INDENIZACOES E RESTITUICOES", "VERBA INDENIZATORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Elemento == "OBRAS E INSTALACOES", "OBRA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Elemento == "DIARIAS - CIVIL", "DIARIAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Favorecido == "COSERN - GRUPO NEOENERGIA", "ENERGIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Favorecido == "CAERN - COMPANHIA DE AGUAS E ESGOTOS DO RN", "AGUA/ESGOTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Favorecido == "BANCO DO BRASIL SA", "BANCO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EMBRATEL", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TELEMAR", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CINTE", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("OI MOVEL", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PUBLICIDADE", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LOCACAO DE MAO DE OBRA", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TERCEIRIZACAO", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RM SERVICES", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MONTECOM", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MAO DE OBRA", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ECT -", pagamentos$Favorecido), "CORREIOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CAPACITACAO", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LOCACOES DE VEICULOS", pagamentos$Favorecido), "LOCACAO DE VEICULO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LOCADORA DE VEICULOS", pagamentos$Favorecido), "LOCACAO DE VEICULO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RENT A CAR", pagamentos$Favorecido), "LOCACAO DE VEICULO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MARKETING", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LINDON", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RATTS", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("INSS", pagamentos$Favorecido), "PREVIDENCIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MOVEIS", pagamentos$Favorecido), "MOBILIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NACIONAL VEICULOS", pagamentos$Favorecido), "AQUISICAO DE VEICULO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CLARO SA", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TOP DOWN", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PENAPI", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("BANCO DE PRECOS", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GR8", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SOGO", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("POSTO", pagamentos$Favorecido), "COMBUSTIVEL", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TRIVALE", pagamentos$Favorecido), "COMBUSTIVEL", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("COMBUSTIVEIS", pagamentos$Favorecido), "COMBUSTIVEL", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SEGURO", pagamentos$Favorecido), "SEGURO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FECAM", pagamentos$Favorecido), "CONTRIBUICOES", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("VIGILANCIA", pagamentos$Favorecido), "SEGURANCA ELETRONICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("23.738.522/0001-90", pagamentos$CPF_CNPJ), "PLACAS/MEDALHAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PLACA", pagamentos$Favorecido), "PLACAS/MEDALHAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CICCARELLI", pagamentos$Favorecido), "LOCACAO DE EQUIPAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Vinculo == "ELETIVO" & pagamentos$Elemento == "DESPESAS DE EXERCICIOS ANTERIORES" & is.na(pagamentos$Objeto), "VERBA INDENIZATORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FOLHA", pagamentos$Favorecido), "FOLHA DE PAGAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FOLHA", pagamentos$Favorecido), "FOLHA DE PAGAMENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("IBRACAP", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DESCONTOS", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("J INACIO", pagamentos$Favorecido), "MATERIAL DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("COMERCIAL JA", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FB MEDEIROS", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SOUZA JUNIOR", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("WALBER CESAR", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FORTEX", pagamentos$Favorecido), "TERCEIRIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LS COMERCIO", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GRAFICA", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CONECTRON", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DEDETIZADORA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ELITE", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CLIMATIZACAO", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GILBERTO DA SILVA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ECIA", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CHAVEIRO", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("40.783.060/0001-42", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("05.454.462/0001-00", pagamentos$CPF_CNPJ), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("08.560.909/0001-06", pagamentos$CPF_CNPJ), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("27.059.350/0001-80", pagamentos$CPF_CNPJ), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CLESIO", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ESAFI", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CEPLAME", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("IDEPE", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("IBC", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("48946702400", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SUPLEMENTO DE FUNDOS", pagamentos$Favorecido), "SUPLEMENTO DE FUNDOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("06.269.447/0001-47", pagamentos$CPF_CNPJ), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("21.764.749/0001-85", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("06.141.142/0001-55", pagamentos$CPF_CNPJ), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("02.598.483/0001-01", pagamentos$CPF_CNPJ), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("34.028.316/0348-65", pagamentos$CPF_CNPJ), "CORREIOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Elemento == "PASSAGENS E DESPESAS COM LOCOMOCAO", "PASSAGENS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ATHENAS", pagamentos$Favorecido), "PASSAGENS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("00.702.550/0001-52", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("13.844.545/0001-26", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("70.045.729/0001-60", pagamentos$CPF_CNPJ), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("24.591.091/0001-45", pagamentos$CPF_CNPJ), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EVENTOS", pagamentos$Favorecido), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("D F DA SILVA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FADO", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CESAR GLAUCIO", pagamentos$Favorecido), "CONSULTORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("VILLACA", pagamentos$Favorecido), "CONSULTORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("LICIDATA", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ITEP", pagamentos$Favorecido), "TAXAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DETRAN", pagamentos$Favorecido), "TAXAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EXATO", pagamentos$Favorecido), "SERVICO DE DIGITALIZACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("17.267.082/0001-38", pagamentos$CPF_CNPJ), "MOBILIARIO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("13.832.648/0001-76", pagamentos$CPF_CNPJ), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("40.761.843/0001-25", pagamentos$CPF_CNPJ), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("11.183.984/0001-00", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("08.170.862/0001-74", pagamentos$CPF_CNPJ), "PREVIDENCIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RADIANY", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EBARA", pagamentos$Favorecido), "MATERIAL DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("32.911.658/0001-41", pagamentos$CPF_CNPJ), "MATERIAL DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("34.997.891/0001-14", pagamentos$CPF_CNPJ), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("24.575.584/0001-91", pagamentos$CPF_CNPJ), "OBRA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CALINE", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("VIANNA", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("IEGESP", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("BONITA", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CLEONE", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("15.289.352/0001-86", pagamentos$CPF_CNPJ), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("08.296.219/0001-91", pagamentos$CPF_CNPJ), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("30.926.352/0001-33", pagamentos$CPF_CNPJ), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ANGELA REGINA", pagamentos$Favorecido), "LOCACAO DE IMOVEL", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("INTGEST", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("HORA CERTA", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CONSELHO", pagamentos$Favorecido), "TAXAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("VOLGA", pagamentos$Favorecido), "EQUIPAMENTO DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FABBRO", pagamentos$Favorecido), "EQUIPAMENTO DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("AOVS", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FABRIKA", pagamentos$Favorecido), "MOBILIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("AZEVEDO E BEZERRA", pagamentos$Favorecido), "ELABORACAO DE PROJETO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NAINFRA", pagamentos$Favorecido), "AQUISIÇÃO DE SMARTPHONES", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RENATA SIQUEIRA", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CA SERVICOS", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("C & P", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("E H M", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DD COMERCIO", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DELTA", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RIOGRANDENSE", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EMPREENDIMENTOS", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ANOTE", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ELEVADORES", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("JOSUEL", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("J & M", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("WEVERTON", pagamentos$Favorecido), "ELABORACAO DE PROJETO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PIZZATTO", pagamentos$Favorecido), "EQUIPAMENTO DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("WISLEY", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("20.532.778/0001-59", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("30.729.998/0001-20", pagamentos$CPF_CNPJ), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("20.399.316/0001-05", pagamentos$CPF_CNPJ), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("01.611.866/0001-00", pagamentos$CPF_CNPJ), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("11.070.662/0001-54", pagamentos$CPF_CNPJ), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ABTDRN", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EBEC", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ABRACAM", pagamentos$Favorecido), "CONTRIBUICOES", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SERVIDORES DE CAMARAS", pagamentos$Favorecido), "CONTRIBUICOES", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NIC.BR", pagamentos$Favorecido), "TAXAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("- DEI", pagamentos$Favorecido), "TAXAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FOSSA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("UNIAO DOS VEREADORES DO BRASIL", pagamentos$Favorecido), "CONTRIBUICOES", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("09.116.070/0001-84", pagamentos$CPF_CNPJ), "NAO CLASSIFICADO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SUPLEMENTO DE FUNDO", pagamentos$Favorecido), "SUPLEMENTO DE FUNDOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("24.365.710/0001-83", pagamentos$CPF_CNPJ), "CONCURSO PUBLICO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TIRADENTES", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("00890861471", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("AUTOPLAC", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DP DE LIMA", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("77839277420", pagamentos$Favorecido), "EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GROUPMED", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MARIA VIVIANE", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PONTO RN", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NATALTECH", pagamentos$Favorecido), "MATERIAL DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RANNY", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MMP", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FGJ", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NORMA ENGENHARIA", pagamentos$Favorecido), "ELABORACAO DE PROJETO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DIRECTCOM", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("09126751445", pagamentos$Favorecido), "PROPAGANDA PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("10.685.202/0001-78", pagamentos$CPF_CNPJ), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("09.129.287/0001-29", pagamentos$CPF_CNPJ), "MOBILIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("05774062481", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("BRUNO GUSTAVO", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CONTEC", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CAIXA", pagamentos$Favorecido), "JUROS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("BRAZ COLOR", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("POLICARD", pagamentos$Favorecido), "CONSIGNADOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CRISLANE", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SAMTAL", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DIJOSETE", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MARUZA", pagamentos$Favorecido), "CONSULTORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CRISTINA GADELHA", pagamentos$Favorecido), "CONSULTORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SOMAR", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PA PRODUCOES", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PORTAL SILVA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("K.L", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("-ISS", pagamentos$Favorecido), "IMPOSTOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("E.B", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("P E J", pagamentos$Favorecido), "PLACAS/MEDALHAS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PRIME", pagamentos$Favorecido), "ELABORACAO DE PROJETO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("J L", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("POLIMAX", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EDITORA CIDADANIA", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("18845177491", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NEW NOW", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SOARES E OLIVEIRA", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("NEGOCIOS PUBLICOS", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CONSULTRE", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("HQZ", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GOODS", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("EQUIPAMIX", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CAMPOS EQUIPAMENTOS", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GARAGEM", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FLAUBER SOARES", pagamentos$Favorecido), "CONSULTORIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("TREINAR", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("WIRECARD", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("PETROGAS", pagamentos$Favorecido), "ELABORACAO DE PROJETO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("VIEIRA DE SOUZA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MVP", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("BORBUREMA", pagamentos$Favorecido), "MANUTENCAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MARIA A.", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RAMON F.", pagamentos$Favorecido), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GLOBAL", pagamentos$Favorecido), "INSCRICAO DE EVENTO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("33", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("DUNNAS", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CASCUDO", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ALEXANDRA MARIA", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("ANTONIO DOMINGOS", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("06682303475", pagamentos$Favorecido), "SOFTWARE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GALIARVA", pagamentos$Favorecido), "COMUNICACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("GO VENDAS", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SRB", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("RCP", pagamentos$Favorecido), "MATERIAL PERMANENTE", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("77841581491", pagamentos$Favorecido), "PROPAGANDA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("MIRANDA COMPUTACAO", pagamentos$Favorecido), "EQUIPAMENTO DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("FRANCISCO JOSE DA SILVA", pagamentos$Favorecido), "OUTROS SERVICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("S D COMERCIO", pagamentos$Favorecido), "EQUIPAMENTO DE INFORMATICA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("SENAC", pagamentos$Favorecido), "CAPACITACAO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("CAVALCANTE &", pagamentos$Favorecido), "MATERIAL DE CONSUMO", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("11.886.312/0001-60", pagamentos$CPF_CNPJ), "SERVICOS GRAFICOS", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(grepl("08.336.975/0001-05", pagamentos$CPF_CNPJ), "MOBILIA", pagamentos$Objeto)
pagamentos$Objeto <- ifelse(pagamentos$Elemento == "DIARIAS - CIVIL", "DIARIAS", pagamentos$Objeto)
pagamentos$Vinculo <- ifelse(grepl("LICIDATA CURSOS LTDA", pagamentos$Favorecido), "PRESTADOR PJ", pagamentos$Vinculo)
pagamentos$Vinculo <- ifelse(grepl("TREINAR -EMPRESA DE TREINAMENTO E TECNOLOGIA EIRELI", pagamentos$Favorecido), "PRESTADOR PJ", pagamentos$Vinculo)
pagamentos$Valor_Pago <- as.numeric(pagamentos$Valor_Pago)
pagamentos <- pagamentos %>%
  group_by(id, Objeto) %>%
  mutate(N_Ocorrencias = n(), 
         Soma_Valor_Pago = sum(Valor_Pago))
saveRDS(pagamentos, file = "Data/pagamentos.rds")
#
df1 <- data.frame(id = pagamentos$id, Valor_Pago = pagamentos$Valor_Pago)
df1$Valor_Pago <- as.numeric(df1$Valor_Pago)
pag_fornecedor <- df1 %>% group_by(id)%>% summarise(Ocorrencias = n(), sum(Valor_Pago))
lista_geral <- readRDS("Data/lista_geral.rds")
pag_fornecedor <- merge(pag_fornecedor, lista_geral[, c("id", "Favorecido")], by = "id", all.x = TRUE)
pag_fornecedor <- select(pag_fornecedor, id, Favorecido, Ocorrencias, 'sum(Valor_Pago)')
pag_fornecedor <- rename(pag_fornecedor, Total_Pago = 'sum(Valor_Pago)')
df1 <- data.frame(id = pagamentos$id, Intervalo = pagamentos$Meses, Primeiro_Pgto = pagamentos$Primeiro_Pgto, Ultimo_Pgto = pagamentos$Ultimo_Pgto, Vinculo = pagamentos$Vinculo)
df1 <- distinct(df1, id, .keep_all = TRUE)
pag_fornecedor <- left_join(pag_fornecedor, df1, by = "id")
saveRDS(pag_fornecedor, file = "Data/pag_fornecedor.rds")
rm(df1)
rm(lista_geral)
#
diarias <- pagamentos
diarias <- subset(diarias, Elemento == "DIARIAS - CIVIL")
colnames(diarias)[11] <- "Meses_Mandato"
diarias <- diarias %>% 
  group_by(Favorecido) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago),
            N_Ocorrencias = n())
saveRDS(diarias, file = "Data/diarias.rds")
#
diarias_vinculo <- subset(pagamentos, Elemento == "DIARIAS - CIVIL")
diarias_vinculo <- diarias_vinculo %>% 
  group_by(Vinculo) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago),
            N_Ocorrencias = n())
diarias_vinculo$Vinculo <- ifelse(grepl("DIARIAS", diarias_vinculo$Vinculo), "NAO CLASSIFICADO", diarias_vinculo$Vinculo)
saveRDS(diarias_vinculo, file = "Data/diarias_vinculo.rds")
#
verbas_indenizatorias <- pagamentos
verbas_indenizatorias <- subset(verbas_indenizatorias, Natureza == 339093)
temp <- pagamentos
temp <- subset(temp, nchar(CPF_CNPJ) != 18)
temp <- subset(temp, Natureza != 339093)
temp <- subset(temp, Natureza != 339036)
temp <- subset(temp, Elemento != "DIARIAS - CIVIL")
temp <- subset(temp, (CPF_CNPJ) != "000001")
temp <- subset(temp, Favorecido != "FOLHA DE PAGAMENTO - CAMARA MUNICIPAL")
temp <- subset(temp, CPF_CNPJ != "000024")
temp <- subset(temp, CPF_CNPJ != "000025")
temp <- subset(temp, CPF_CNPJ != "000026")
temp <- subset(temp, CPF_CNPJ != "000032")
temp <- subset(temp, CPF_CNPJ != "##1.714.174-##")
temp <- subset(temp, CPF_CNPJ != "##1.367.324-##")
temp <- subset(temp, CPF_CNPJ != "##1.451.904-##")
verbas_i_atrasadas <- temp
verbas_indenizatorias <- rbind(verbas_indenizatorias, verbas_i_atrasadas)
verbas_indenizatorias <- verbas_indenizatorias %>% 
  group_by(Favorecido) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago),
            N_Ocorrencias = n())
saveRDS(verbas_indenizatorias, file = "Data/verbas_indenizatorias.rds")
rm(temp)
rm(verbas_i_atrasadas)
#
pagamentos_PJ <- pagamentos
pagamentos_PJ <- subset(pagamentos_PJ, nchar(CPF_CNPJ) == 18)
PJ_erro_cadastro <- pagamentos[pagamentos$CPF_CNPJ %in% c("000025", "000032"), ]
pagamentos_PJ <- rbind(pagamentos_PJ, PJ_erro_cadastro)
pagamentos_PJ <- pagamentos_PJ %>% 
  group_by(Favorecido) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago),
            N_Ocorrencias = n())
favorecidos_unicos <- unique(pagamentos$Favorecido)
dados_resumo <- data.frame(Favorecido = favorecidos_unicos,
                           Objeto = pagamentos[!duplicated(pagamentos$Favorecido),]$Objeto)
pagamentos_PJ <- merge(pagamentos_PJ, dados_resumo[, c("Favorecido", "Objeto")], by = "Favorecido")
saveRDS(pagamentos_PJ, file = "Data/pagamentos_PJ.rds")
rm(dados_resumo)
rm(PJ_erro_cadastro)
rm(favorecidos_unicos)
#
pagamentos_objeto <- pagamentos
pagamentos_objeto <- pagamentos_objeto %>%
  group_by(Objeto) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago))
saveRDS(pagamentos_objeto, file = "Data/pagamentos_objeto.rds")
#
pagamentos_PF <- pagamentos
pagamentos_PF <- subset(pagamentos_PF, Natureza == 339036)
suprimento_fundo <- pagamentos[pagamentos$CPF_CNPJ %in% c("000024", "000026"), ]
PF_erro_cadastro <- subset(pagamentos, CPF_CNPJ == "##1.714.174-##")
PF_erro_cadastro <- subset(PF_erro_cadastro, Elemento == "OUTROS SERVICOS DE TERCEIROS - PESSOA JURIDICA")
outros_PF <- pagamentos[pagamentos$CPF_CNPJ %in% c("##1.367.324-##", "##1.451.904-##"), ]
pagamentos_PF <- rbind(pagamentos_PF, suprimento_fundo, PF_erro_cadastro, outros_PF)
pagamentos_PF <- pagamentos_PF %>% 
  group_by(Favorecido) %>%
  summarise(Primeiro_Pgto = min(Primeiro_Pgto),
            Ultimo_Pgto = max(Ultimo_Pgto),
            Total_Pago = sum(Valor_Pago),
            N_Ocorrencias = n())
favorecidos_unicos <- unique(pagamentos$Favorecido)
dados_resumo <- data.frame(Favorecido = favorecidos_unicos,
                           Objeto = pagamentos[!duplicated(pagamentos$Favorecido),]$Objeto)
pagamentos_PF <- merge(pagamentos_PF, dados_resumo[, c("Favorecido", "Objeto")], by = "Favorecido")
saveRDS(pagamentos_PF, file = "Data/pagamentos_PF.rds")
rm(PF_erro_cadastro)
rm(suprimento_fundo)
rm(favorecidos_unicos)
#